config/routes.rb
Spree::Core::Engine.append_routes do
	namespace :admin do
		resources :user_groups do
			member do
				get :pricing
				patch :pricing
			end
		end
	end
end

app/models/spree/user_group.rb
class Spree::UserGroup < ActiveRecord::Base
  has_many :users, :dependent => :nullify
  validates :name, :presence => true
  has_many :user_groups_variants
  has_many :variants, :through => :user_groups_variants

  extend Spree::DisplayMoney
  money_methods :minimum_order

  include Spree::CalculatedAdjustments
  
  def calculator_description
    return Spree.t(:none) if calculator.nil?
    calculator.description
  end

  def price_for_variant variant, orig_price
    if calculator.is_a?(Spree::Calculator::PerVariantPricing)
      user_groups_variants.where(variant: variant).first.try(:price)
    else
      calculator.compute_item(variant, orig_price)
    end
  end
end

app/controllers/spree/admin/user_groups_controller.rb
class Spree::Admin::UserGroupsController < Spree::Admin::ResourceController
  before_filter :load_data


  def pricing
    params[:price][params[:id]].each do |k,v|
      ugv = Spree::UserGroupsVariant.where(:user_group_id => params[:id]).where(:variant_id => k).first
      ugv.destroy if v == '' and ugv
      next if v == ''
      ugv.update_attributes(:price => v) if ugv and ugv.price
      next if ugv
      Spree::UserGroupsVariant.create!(:user_group_id => params[:id], :variant_id => k, :price => v)
      flash.notice = Spree.t(:variant_pricing_updated_successfully)
    end if params[:price]
  end
  
  private
  def build_object
    @object ||= end_of_association_chain.send((parent? ? :build : :new), object_params)
    @object.calculator = params[:user_group][:calculator_type].constantize.new if params[:user_group]
  end

  def load_data
    @calculators = Spree::UserGroup.calculators
  end
end

app/views/spree/admin/user_groups/_form.html.erb
<div data-hook="admin_user_group_form_fields" class="row">
  <div data-hook="admin_user_group_form_name_field" class="col-md-6">
    <%= f.field_container :name, class: ['form-group'] do %>
      <%= f.label :name, Spree.t(:name) %> <span class="required">*</span>
      <%= f.text_field :name, :class => 'form-control' %>
      <%= f.error_message_on :name %>
    <% end %>
  </div>
  <div data-hook="admin_user_group_form_name_field" class="col-md-6">
    <%= f.field_container :minimum_order, class: ['form-group'] do %>
      <%= f.label :minimum_order, Spree.t(:minimum_order) %> <span class="required">*</span>
      <%= f.text_field :minimum_order, :class => 'form-control' %>
      <%= f.error_message_on :minimum_order %>
    <% end %>
  </div>
  <div class="col-md-12">
    <div data-hook="admin_user_group_form_calculator_fields" class="col-md-6">
      <%= render :partial => 'spree/admin/shared/calculator_fields', :locals => { :f => f } %>
    </div>
  </div>
</div>

app/views/spree/admin/user_groups/_pricing_form.html.erb
<% curr_product_id = nil %>
<table class="table" id='listing_user_group_variants'>
  <% Spree::Variant.order(:product_id).each do |v| %>
    <% if curr_product_id != v.product_id %>
      <% curr_product_id = v.product_id %>
      <tr>
        <td colspan="3"></td>
      </tr>
      <tr>
        <td colspan="3">
          <strong><%= v.product.name %></strong>
        </td>
      </tr>
    <% end %>

    <% ugv = Spree::UserGroupsVariant.where(:user_group_id => @user_group).where(:variant_id => v).first %>
    <tr>
      <td>
        <%= variant_options(v) || Spree.t(:master) %> (<%= v.sku %>)
      </td>
      <td>
        Base Price (<%= v.display_price || Spree.t(:master).downcase %>)
      <td>
        <div data-hook="price" class="field">
          <%= text_field_tag "price[#{@user_group.id}][#{v.id}]", (ugv.price if ugv), :class => 'form-control' %>
        </div>
      </td>
    </tr>
  <% end %>
</table>

app/views/spree/admin/user_groups/edit.html.erb
<% content_for :page_title do %>
  <%= Spree.t(:editing_user_group) %>
<% end %>

<% content_for :page_actions do %>
  <li>
    <%= button_link_to Spree.t(:back_to_user_groups_list), spree.admin_user_groups_path, :icon => 'arrow-left' %>
  </li>
<% end %>

<div data-hook="admin_user_group_edit_form_header">
  <%= render :partial => 'spree/shared/error_messages', :locals => { :target => @user_group } %>
</div>

<div data-hook="admin_user_group_edit_form">
  <%= form_for [:admin, @user_group] do |f| %>
    <fieldset class="no-border-top">
      <%= render :partial => 'form', :locals => { :f => f } %>

      <div class="clear"></div>

      <div data-hook="admin_user_group_edit_form_buttons">
        <%= render :partial => 'spree/admin/shared/edit_resource_links' %>
      </div>
    </fieldset>
  <% end %>
</div>

app/views/spree/admin/user_groups/index.html.erb
<% content_for :page_title do %>
  <%= Spree.t(:user_groups) %>
<% end %>

<% content_for :page_actions do %>
  <%= button_link_to Spree.t(:new_user_group), new_object_url, :icon => 'plus', :id => 'admin_new_user_group_link', class: 'btn-success' %>
<% end %>

<% if @user_groups.any? %>
  <table class="table" id='listing_user_groups'>
    <thead>
    <tr data-hook="admin_user_groups_index_headers">
      <th><%= Spree.t(:name) %></th>
      <th><%= Spree.t(:calculator) %></th>
      <th><%= Spree.t(:minimum_order) %></th>
      <th data-hook="admin_user_groups_index_header_actions" class="actions"></th>
    </tr>
    </thead>
    <tbody>
    <% @user_groups.includes(:calculator).each do |user_group| %>
      <tr id="<%= spree_dom_id user_group %>" data-hook="admin_user_groups_index_rows" class="<%= cycle('odd', 'even') %>">
        <td class="align-center"><%= user_group.name %></td>
        <td class="align-center"><%= user_group.calculator_description %></td>
        <td class="align-center"><%= user_group.display_minimum_order %></td>
        <td data-hook="admin_user_groups_index_row_actions" class="actions">
          <%= link_to_with_icon('usd', Spree.t(:per_variant_pricing), pricing_admin_user_group_path(user_group.id), {:data => {:action => 'edit'}, class: 'btn btn-default btn-sm', :no_text => true}) if user_group.calculator.class == Spree::Calculator::PerVariantPricing %>
          <%= link_to_edit user_group, :no_text => true %>
          <%= link_to_delete user_group, :no_text => true %>
      </tr>
    <% end %>
    <% if @user_groups.empty? %>
      <tr>
        <td colspan="3"><%= Spree.t(:none) %></td>
      </tr>
    <% end %>
    </tbody>
  </table>
<% else %>
  <div class="alert alert-info no-objects-found">
    <%= Spree.t(:no_resource_found, resource: I18n.t(:other, scope: 'activerecord.models.spree/user_group')) %>,
    <%= link_to Spree.t(:add_one), spree.new_admin_user_group_path %>!
  </div>
<% end %>

app/views/spree/admin/user_groups/new.html.erb
<% content_for :page_title do %>
  <%= Spree.t(:new_user_group) %>
<% end %>

<% content_for :page_actions do %>
  <%= button_link_to Spree.t(:back_to_user_groups_list), spree.admin_user_groups_path, :icon => 'arrow-left' %>
<% end %>

<div data-hook="admin_user_group_new_form_header">
  <%= render :partial => 'spree/shared/error_messages', :locals => { :target => @user_group } %>
</div>

<div data-hook="admin_user_group_new_form">
  <%= form_for [:admin, @user_group] do |f| %>
    <fieldset>
      <%= render :partial => 'form', :locals => { :f => f } %>
      <%= render partial: 'spree/admin/shared/new_resource_links' %>
    </fieldset>
  <% end %>
</div>

app/views/spree/admin/user_groups/pricing.html.erb
<% content_for :page_title do %>
  <%= Spree.t(:per_variant_pricing_for) %> <%= @user_group.name %>
<% end %>

<% content_for :page_actions do %>
  <%= button_link_to Spree.t(:back_to_user_groups_list), spree.admin_user_groups_path, :icon => 'arrow-left' %>
<% end %>

<div data-hook="admin_user_group_edit_form_header">
  <%= render :partial => 'spree/shared/error_messages', :locals => {:target => @user_group} %>
</div>

<div data-hook="admin_user_group_edit_form">
  <%= form_for [:admin, @user_group], url: pricing_admin_user_group_url(@user_group) do |f| %>
    <fieldset>
      <%= render :partial => 'pricing_form', :locals => {:f => f} %>
      <%= render :partial => 'spree/admin/shared/edit_resource_links' %>
    </fieldset>
  <% end %>
</div>